name: Chatty
version: ${project.version}
main: ru.mrbrikster.chatty.Chatty
authors: [MrBrikster]

# Essentials needed only for overwriting existing private-messaging commands.
loadbefore: [Essentials]
softdepend: [Vault, PlaceholderAPI, NametagEdit]
