# ******************************************************
# * Chatty (version ${project.version})
#   Universal chat-system for Bukkit-server.
#
#   Creator: MrBrikster
#
# * Optional dependencies:
#   Vault, PlaceholderAPI, NameTagEdit.
# ******************************************************

# * GENERAL
#
# Very important settings.
general:
  # Plugin localization.
  #
  # en - English.
  # ru - Russian.
  # de - German.
  locale: en

  # Chat listener priority.
  # Possible values:
  # lowest, low, normal, high, highest.
  priority: low

  # Chat logging in "Chatty/logs".
  log: true

  # Completely cancels chat events,
  # if it cancels by moderation method
  # (instead of clearing recipients).
  completely-cancel: false

  # Storage player data mode.
  # true - for online-mode servers and servers under BungeeCord.
  # false - for offline-mode servers.
  uuid: false

# * CHATS
#
# On the server there can be different chats with different settings,
# whether it's donate-chat, admin-chat, or the usual local and global.
#
# Permissions:
# chatty.chat.<chat> - permission for both writing and seeing messages.
# chatty.chat.<chat>.write - permission for writing messages.
# chatty.chat.<chat>.see - permission for seeing messages.
#
# Chat has the following options:
# enable - on/off chat.
# format - chat formatting string.
# range - chat range. -1 to world-wide chat, -2 to server-wide chat.
# symbol - the character from which the messages begin.
# cooldown - message cooldown in seconds (bypass permission - chatty.cooldown.<chat>).
# money - message price (depends on Vault).
# permission - should this chat use permissions? Default value is true.
chats:
  local:
    enable: true
    format: '[Local] {prefix}{player}{suffix}: {message}'
    range: 100
    cooldown: -1

  global:
    enable: true
    format: '[Global] {prefix}{player}{suffix}: {message}'
    range: -1
    symbol: '!'
    cooldown: -1

# * PRIVATE MESSAGING
pm:
  # Enables private messaging function.
  enable: true

  # Allows console to messaging players
  # and messaging players to console.
  allow-console: false

  # Format of messages
  #
  # Variables:
  # {sender-name}, {recipient-name} - nicknames of sender and recipient.
  # {sender-prefix}, {recipient-prefix} - prefixes of sender and recipient.
  # {sender-suffix}, {recipient-suffix} - suffixes of sender and recipient.
  # {message} - private message.
  format:
    recipient: '&7{sender-prefix}{sender-name} &6-> &7{recipient-prefix}{recipient-name}: &f{message}'
    sender: '&7{sender-prefix}{sender-name} &6-> &7{recipient-prefix}{recipient-name}: &f{message}'

  commands:
    msg:
      # Enables "/msg" command.
      # Permission: chatty.command.msg
      enable: true
      # Aliases for "/msg" command.
      aliases: ['message', 'pm', 'm', 'w']

    reply:
      # Enables "/reply" command.
      # Permission: chatty.command.reply
      enable: true
      # Aliases for "/reply" command.
      aliases: ['r']

    ignore:
      # Enables "/ignore" command.
      # Permission: chatty.command.ignore
      enable: true
      # Aliases for "/ignore" command.
      aliases: []

# * SPY
#
# Mode for spying for chat and private messages.
spy:
  enable: true

  # Spy-mode message format.
  format:
    # Permission: chatty.spy.<chat
    chat: '&6[Spy] &r{format}'

    # Permission: chatty.spy.pm
    #
    # Uses sender format of PM.
    pm: '&6[Spy] &r{format}'

# * JSON
#
# Chat formatting with additional interactive features.
#
# 1.7.10 and newer.
json:
  enable: false

  # Command that executes (by player) when you click on the player's name.
  # Supports PlaceholderAPI.
  # *** You should use "command" OR "suggest_command" OR "link" and cannot combine.
  #
  # You can use "{player}" variable here.
  command: /home

  # Command that suggests when you click on the player's name.
  # Supports PlaceholderAPI.
  # *** You should use "command" OR "suggest_command" OR "link" and cannot combine.
  #
  # You can use "{player}" variable here.
  suggest_command: '/msg {player} '

  # URL that opens when when you click on the player's name.
  # You must use "http://" or "https://" prefix, else you will crash Minecraft client :D
  #
  # Supports PlaceholderAPI.
  #
  # You can use "{player}" variable here.
  link: 'http://google.com'

  # Hover tooltip for the player's name.
  # Supports PlaceholderAPI.
  #
  # You can use "{player}" variable here.
  tooltip:
  - '&fPlayer &e{player}'
  - '&fThis tooltip supports'
  - '&fPlaceholderAPI placeholders!'

  # Swears hovers.
  #
  # Permission: chatty.swears.see
  swears:
    enable: true
    tooltip:
    - '&o{word}'
    - ''
    - '&eClick here to add word to whitelist.'
    suggest_command: /swears add {word}

  # Replacements for chat formats.
  #
  # You can replace plain text with JSON-pieces
  # to make chat more interactive.
  #
  # Available properties:
  # text, tooltip, command, suggest_command, link.
  replacements:
    'Admin':
      # Original text.
      original: '&cAdmin'
      # Text to replace.
      #
      # Supports PlaceholderAPI.
      # You can use "{player}" variable here.
      #
      # You can remove this line, if you need original text.
      text: '&cAdmin'

      # Hover tooltip for the text.
      #
      # Supports PlaceholderAPI.
      #
      # You can use "{player}" variable here.
      tooltip:
      - '&cThis is admin.'
      - '&4&lBe afraid of him!'
      - ''
      - '&eClick here to see the server rules.'

      # *** You should use "command" OR "suggest_command" OR "link" and cannot combine.
      # Command that executes when you click on the text.
      #
      # Supports PlaceholderAPI.
      #
      # You can use "{player}" variable here.
      command: /rules

# * NOTIFICATIONS
#
# There are three types of notifications:
# via Chat, ActionBar (1.8 and newer) and Advancements (1.12 and newer).
notifications:
  # Chat notifications.
  chat:
    # On/off chat notifications.
    enable: true
    # Notification lists.
    lists:
      # List "default".
      # Permission: chatty.notification.chat.default
      default:
        # Messages interval.
        time: 60
        # Messages prefix.
        prefix: ''
        # List of messages.
        messages:
        - '&cThe server is using Chatty!\n&fOur address: 127.0.0.1\n&fVisit out site: example.com'
        - '&aThe server is using Chatty!'
        # Disable permission checking.
        # Delete the line, if you need this.
        permission: false

  # ActionBar notifications.
  # It's static notifications,
  # which changes the message with interval.
  #
  # Permission: chatty.notification.actionbar
  actionbar:
    # On/off ActionBar notifications.
    # Only 1.8+.
    enable: false
    # One message time.
    time: 60
    # Messages prefix.
    prefix: ''
    # List of messages.
    messages:
    - '&cThe server is using Chatty!'
    - '&aThe server is using Chatty!'
    # Disable permission checking.
    # Delete the line, if you need this.
    permission: false

  # Title notifications.
  title:
    # On/off title notifications.
    enable: true
    # Notification lists.
    lists:
      # List "default".
      # Permission: chatty.notification.title.default
      default:
        # Messages interval.
        time: 60
        # List of messages.
        messages:
        - '&cThe server is using Chatty!\n&eOur address: 127.0.0.1'
        - '&aThe server is using Chatty!'
        # Disable permission checking.
        # Delete the line, if you need this.
        permission: false

  # Advancements (Achievements) notifications.
  advancements:
    # Advancements notifications.
    # Only 1.12 and newer.
    enable: false
    # Notification lists.
    lists:
      # List "default".
      # Permission: chatty.notification.advancements.default
      default:
        # Messages interval.
        time: 60
        # List of messages.
        messages:
        - icon: 'minecraft:diamond'
          header: '&bChatty v.${project.version}'
          footer: '&fThank you for using!'
        - icon: 'minecraft:gold_ingot'
          header: '&eChatty v.${project.version}'
          footer: '&fThank you for using!'
        # Disable permission checking.
        # Delete the line, if you need this.
        permission: false

# * MODERATION
#
# Automatic chat moderation tools.
moderation:
  caps:
    # On/off caps protection.
    # Bypass permission: chatty.moderation.caps
    enable: true
    # Minimal length of message to caps checking.
    length: 6
    # Minimal upper case percent for caps.
    percent: 80
    # On/off caps message blocking.
    # When false, message will be sent in lower case.
    block: true

  advertisement:
    # On/off advertisement protection.
    # Bypass permission: chatty.moderation.advertisement
    enable: true
    # Regular expressions for IP-addresses and sites.
    patterns:
      ip: '(?:\d{1,3}[.,-:;\/()=?}+ ]{1,4}){3}\d{1,3}'
      web: '[-a-zA-Z0-9@:%_\+.~#?&//=]{2,256}\.[a-z]{2,4}\b(\/[-a-zA-Z0-9@:%_\+~#?&//=]*)?'
    # On/off caps message blocking.
    # When false, advertisements will be replaced.
    block: true
    # Replacement for advertisement.
    replacement: '<advertisement>'
    # Whitelisted IP-addresses and sites.
    whitelist:
    - 'example.com'
    - 'vk.com'
    - 'google.com'
    - 'youtube.com'
    - 'yandex.ru'
    - '192.168.1.1'
    - '127.0.0.1'

  swear:
    # On/off swear protection.
    # Bypass permission: chatty.moderation.swear
    enable: false
    # On/off swear message blocking.
    # When false, swears will be replaced.
    block: true
    # Replacement for swears.
    replacement: '<swear>'
    # Swear-list configuration: "Chatty/swears"

# * MISCELLANEOUS
miscellaneous:
  commands:
    # Permission: chatty.command.clearchat
    clearchat:
      enable: true
      aliases: ['chatclear']

    # Permission: chatty.command.prefix
    prefix:
      enable: true
      # Automatically adds a string after prefix.
      after-prefix: ' '
      # Limits prefix length (inclusive "after-prefix")
      length-limit: 16
      # Auto-applying in NametagEdit.
      # (Requires NameTagEdit plugin).
      auto-nte: false

    # Permission: chatty.command.suffix
    suffix:
      enable: true
      # Automatically adds a string before suffix.
      before-suffix: ' '
      # Limits suffix length (inclusive "before-suffix")
      length-limit: 16
      # Auto-applying in NametagEdit.
      # (Requires NameTagEdit plugin).
      auto-nte: false

  # Change default Minecraft messages.
  vanilla:
    join:
      enable: true

      message: '&e{prefix}{player}{suffix} &ejoined the server.'

      # Permission: chatty.misc.joinmessage
      permission: false
    quit:
      enable: true

      message: '&e{prefix}{player}{suffix} &eleft the server.'

      # Permission: chatty.misc.quitmessage
      permission: false
    death:
      enable: true

      message: '&e{prefix}{player}{suffix} &edied.'

      # Permission: chatty.misc.deathmessage
      permission: false

config-version: 2.0