name: ${project.name}
version: ${project.version}
main: ${project.groupId}.${project.artifactId}.${project.name}
authors: [MrBrikster]

# Essentials needed only for overwriting existing private-messaging commands.
softdepend: [Vault, PlaceholderAPI, NametagEdit, Essentials]
